import type { Meeting, Opportunity, BigBet, Funding } from './types'

export const meetings: Meeting[] = [
  {
    id: 'm1',
    title: 'SIC Agentforce - Total Energies',
    type: 'SIC',
    date: '2026-06-10',
    account: 'Total Energies',
    opportunityId: 'o1',
    owner: 'Pierre Medevielle',
    status: 'scheduled',
    preparation: 'in_progress',
    attendees: ['CIO', 'CDO', 'VP Operations'],
    location: 'La Défense',
    notes: 'Préparer démo Agentforce Service + ROI calculator énergie',
  },
  {
    id: 'm2',
    title: 'Demo Agentforce Sales - LVMH',
    type: 'Demo',
    date: '2026-06-12',
    account: 'LVMH',
    opportunityId: 'o2',
    owner: 'Pierre Medevielle',
    status: 'scheduled',
    preparation: 'ready',
    attendees: ['CMO', 'Head of Digital', 'IT Director'],
    location: 'Paris 8ème',
    notes: 'Focus sur personnalisation client et service après-vente luxury',
  },
  {
    id: 'm3',
    title: 'QBR Q2 - BNP Paribas',
    type: 'QBR',
    date: '2026-06-15',
    account: 'BNP Paribas',
    opportunityId: 'o3',
    owner: 'Pierre Medevielle',
    status: 'scheduled',
    preparation: 'not_started',
    attendees: ['CIO', 'VP Digital Banking', 'Procurement'],
    location: 'Paris 9ème',
  },
  {
    id: 'm4',
    title: 'SIC Agentforce - Société Générale',
    type: 'SIC',
    date: '2026-06-20',
    account: 'Société Générale',
    opportunityId: 'o4',
    owner: 'Pierre Medevielle',
    status: 'scheduled',
    preparation: 'in_progress',
    attendees: ['CDTO', 'Head of Innovation', 'CFO'],
    location: 'La Défense',
    notes: 'Suite du discovery - présenter proposition valeur Agentforce FS',
  },
  {
    id: 'm5',
    title: 'Discovery Renault Group',
    type: 'Discovery',
    date: '2026-06-18',
    account: 'Renault Group',
    opportunityId: 'o7',
    owner: 'Pierre Medevielle',
    status: 'scheduled',
    preparation: 'not_started',
    attendees: ['Head of Connected Services', 'IT Architect'],
    location: 'Boulogne-Billancourt',
  },
  {
    id: 'm6',
    title: 'POV Review - Carrefour',
    type: 'POV',
    date: '2026-06-05',
    account: 'Carrefour',
    opportunityId: 'o5',
    owner: 'Pierre Medevielle',
    status: 'completed',
    preparation: 'ready',
    notes: 'POV concluant - passage en négociation. KPIs atteints.',
  },
  {
    id: 'm7',
    title: 'EBC Salesforce HQ - AXA',
    type: 'EBC',
    date: '2026-06-30',
    account: 'AXA',
    opportunityId: 'o9',
    owner: 'Pierre Medevielle',
    status: 'scheduled',
    preparation: 'not_started',
    attendees: ['CEO', 'CDTO', 'CDO', 'VP Claims'],
    location: 'San Francisco (EBC)',
    notes: 'Organiser EBC à SF - aligner avec équipe produit Agentforce',
  },
  {
    id: 'm8',
    title: 'Workshop Agentforce - Orange',
    type: 'Workshop',
    date: '2026-06-25',
    account: 'Orange',
    opportunityId: 'o8',
    owner: 'Pierre Medevielle',
    status: 'scheduled',
    preparation: 'not_started',
    attendees: ['Head of BSS', 'VP Customer Experience', 'Architects x3'],
    location: 'Paris 15ème',
  },
  {
    id: 'm9',
    title: 'Négociation Contrat - SNCF',
    type: 'Negotiation',
    date: '2026-06-08',
    account: 'SNCF',
    opportunityId: 'o11',
    owner: 'Pierre Medevielle',
    status: 'scheduled',
    preparation: 'in_progress',
    attendees: ['Procurement Director', 'Legal', 'CIO'],
    location: 'Paris Saint-Lazare',
    notes: 'Aligner pricing et T&Cs - impliquer Legal Salesforce',
  },
  {
    id: 'm10',
    title: 'Demo Agentforce MFG - Schneider Electric',
    type: 'Demo',
    date: '2026-07-02',
    account: 'Schneider Electric',
    opportunityId: 'o10',
    owner: 'Pierre Medevielle',
    status: 'scheduled',
    preparation: 'not_started',
    attendees: ['CDO', 'VP Manufacturing IT'],
    location: 'Rueil-Malmaison',
  },
  {
    id: 'm11',
    title: 'SIC Agentforce - Air France',
    type: 'SIC',
    date: '2026-06-08',
    account: 'Air France',
    opportunityId: 'o6',
    owner: 'Pierre Medevielle',
    status: 'scheduled',
    preparation: 'in_progress',
    attendees: ['CIO', 'Head of Customer Service', 'Digital Director'],
    location: 'Roissy CDG',
    notes: 'Focus disruption service + cas usage agents autonomes',
  },
]

export const opportunities: Opportunity[] = [
  {
    id: 'o1',
    name: 'Total Energies - Agentforce Service',
    account: 'Total Energies',
    amount: 1200000,
    closeDate: '2026-09-30',
    quarter: 'Q3',
    fiscalYear: 2027,
    stage: '5 - Value Proposition',
    type: 'New Business',
    bigBetId: 'bb3',
    fundingIds: ['f1'],
    owner: 'Pierre Medevielle',
    nextStep: 'SIC le 10/06 - Préparer business case ROI',
    agentforceProducts: ['Agentforce Service Cloud', 'Einstein Analytics'],
    probability: 50,
  },
  {
    id: 'o2',
    name: 'LVMH - Agentforce Sales & Service',
    account: 'LVMH',
    amount: 800000,
    closeDate: '2026-09-15',
    quarter: 'Q3',
    fiscalYear: 2027,
    stage: '4 - Proposal',
    type: 'New Business',
    bigBetId: 'bb2',
    fundingIds: ['f2'],
    owner: 'Pierre Medevielle',
    nextStep: 'Demo 12/06 - Soumettre proposal semaine suivante',
    agentforceProducts: ['Agentforce Sales Cloud', 'Agentforce Service Cloud'],
    probability: 40,
  },
  {
    id: 'o3',
    name: 'BNP Paribas - Agentforce Platform',
    account: 'BNP Paribas',
    amount: 2500000,
    closeDate: '2026-12-31',
    quarter: 'Q4',
    fiscalYear: 2027,
    stage: '3 - Discovery',
    type: 'New Business',
    bigBetId: 'bb1',
    fundingIds: ['f3'],
    owner: 'Pierre Medevielle',
    nextStep: 'QBR 15/06 - Identifier champion interne',
    agentforceProducts: ['Agentforce Platform', 'Data Cloud'],
    probability: 20,
  },
  {
    id: 'o4',
    name: 'Société Générale - Agentforce Financial Services',
    account: 'Société Générale',
    amount: 1800000,
    closeDate: '2026-09-30',
    quarter: 'Q3',
    fiscalYear: 2027,
    stage: '6 - Negotiation',
    type: 'New Business',
    bigBetId: 'bb1',
    fundingIds: ['f5'],
    owner: 'Pierre Medevielle',
    nextStep: 'SIC 20/06 - Finaliser T&Cs et pricing',
    agentforceProducts: ['Agentforce for Financial Services', 'Einstein'],
    probability: 70,
  },
  {
    id: 'o5',
    name: 'Carrefour - Agentforce Commerce',
    account: 'Carrefour',
    amount: 600000,
    closeDate: '2026-06-30',
    quarter: 'Q2',
    fiscalYear: 2027,
    stage: '7 - Closed Won',
    type: 'New Business',
    bigBetId: 'bb2',
    owner: 'Pierre Medevielle',
    nextStep: 'Kick-off implémentation juillet',
    agentforceProducts: ['Agentforce Commerce Cloud', 'Einstein AI'],
    probability: 100,
  },
  {
    id: 'o6',
    name: 'Air France - Agentforce Service',
    account: 'Air France',
    amount: 950000,
    closeDate: '2026-09-30',
    quarter: 'Q3',
    fiscalYear: 2027,
    stage: '4 - Proposal',
    type: 'New Business',
    bigBetId: 'bb4',
    owner: 'Pierre Medevielle',
    nextStep: 'SIC 08/06 - Préparer proposal disruption service',
    agentforceProducts: ['Agentforce Service Cloud', 'Agentforce Flex'],
    probability: 40,
  },
  {
    id: 'o7',
    name: 'Renault Group - Agentforce Manufacturing',
    account: 'Renault Group',
    amount: 1400000,
    closeDate: '2026-12-31',
    quarter: 'Q4',
    fiscalYear: 2027,
    stage: '3 - Discovery',
    type: 'New Business',
    bigBetId: 'bb3',
    fundingIds: ['f8'],
    owner: 'Pierre Medevielle',
    nextStep: 'Discovery 18/06 - Mapper use cases',
    agentforceProducts: ['Agentforce for Manufacturing', 'Field Service'],
    probability: 20,
  },
  {
    id: 'o8',
    name: 'Orange - Agentforce Telco',
    account: 'Orange',
    amount: 2100000,
    closeDate: '2026-12-31',
    quarter: 'Q4',
    fiscalYear: 2027,
    stage: '2 - Qualification',
    type: 'New Business',
    bigBetId: 'bb4',
    fundingIds: ['f4'],
    owner: 'Pierre Medevielle',
    nextStep: 'Workshop 25/06 - Qualifier budget et timeline',
    agentforceProducts: ['Agentforce Platform', 'Agentforce Service'],
    probability: 10,
  },
  {
    id: 'o9',
    name: 'AXA - Agentforce Insurance',
    account: 'AXA',
    amount: 1600000,
    closeDate: '2026-09-30',
    quarter: 'Q3',
    fiscalYear: 2027,
    stage: '5 - Value Proposition',
    type: 'New Business',
    bigBetId: 'bb1',
    fundingIds: ['f6'],
    owner: 'Pierre Medevielle',
    nextStep: 'EBC 30/06 - Préparer exec alignment SF HQ',
    agentforceProducts: ['Agentforce for Financial Services', 'Einstein Claims'],
    probability: 50,
  },
  {
    id: 'o10',
    name: 'Schneider Electric - Agentforce MFG',
    account: 'Schneider Electric',
    amount: 1100000,
    closeDate: '2026-12-31',
    quarter: 'Q4',
    fiscalYear: 2027,
    stage: '3 - Discovery',
    type: 'New Business',
    bigBetId: 'bb3',
    owner: 'Pierre Medevielle',
    nextStep: 'Demo 02/07 - Identifier use cases prioritaires',
    agentforceProducts: ['Agentforce for Manufacturing', 'Field Service AI'],
    probability: 20,
  },
  {
    id: 'o11',
    name: 'SNCF - Agentforce Service',
    account: 'SNCF',
    amount: 750000,
    closeDate: '2026-09-30',
    quarter: 'Q3',
    fiscalYear: 2027,
    stage: '6 - Negotiation',
    type: 'New Business',
    bigBetId: 'bb5',
    owner: 'Pierre Medevielle',
    nextStep: 'Négociation 08/06 - Finaliser contrat Q3',
    agentforceProducts: ['Agentforce Service Cloud', 'Einstein AI'],
    probability: 70,
  },
  {
    id: 'o12',
    name: 'Capgemini - Agentforce Platform (GSI)',
    account: 'Capgemini',
    amount: 3200000,
    closeDate: '2026-12-31',
    quarter: 'Q4',
    fiscalYear: 2027,
    stage: '2 - Qualification',
    type: 'New Business',
    fundingIds: ['f7'],
    owner: 'Pierre Medevielle',
    nextStep: 'Qualifier scope et modèle commercial GSI',
    agentforceProducts: ['Agentforce Platform', 'Partner Program'],
    probability: 10,
  },
]

export const bigBets: BigBet[] = [
  {
    id: 'bb1',
    name: 'Financial Services Hub',
    description: 'Dominer le segment Banque & Assurance avec Agentforce for Financial Services. Cibler les top 10 FS accounts français.',
    category: 'Financial Services',
    quarters: ['Q3', 'Q4'],
    priority: 'high',
    opportunityIds: ['o3', 'o4', 'o9'],
    status: 'on_track',
    owner: 'Pierre Medevielle',
    targetRevenue: 5900000,
    currentRevenue: 1800000,
    keyAccounts: ['BNP Paribas', 'Société Générale', 'AXA', 'Crédit Agricole'],
  },
  {
    id: 'bb2',
    name: 'Retail & Luxury Wave',
    description: 'Capitaliser sur la transformation digitale retail et luxury. Focus Commerce Cloud + Agentforce agents.',
    category: 'Retail & Commerce',
    quarters: ['Q2', 'Q3'],
    priority: 'high',
    opportunityIds: ['o2', 'o5'],
    status: 'on_track',
    owner: 'Pierre Medevielle',
    targetRevenue: 2500000,
    currentRevenue: 1400000,
    keyAccounts: ['LVMH', 'Carrefour', 'L\'Oréal', 'Kering'],
  },
  {
    id: 'bb3',
    name: 'Manufacturing & Energy Transformation',
    description: 'Agentforce pour la transformation industrie - field service AI, operations, maintenance prédictive.',
    category: 'Manufacturing & Energy',
    quarters: ['Q3', 'Q4'],
    priority: 'high',
    opportunityIds: ['o1', 'o7', 'o10'],
    status: 'at_risk',
    owner: 'Pierre Medevielle',
    targetRevenue: 3700000,
    currentRevenue: 0,
    keyAccounts: ['Total Energies', 'Renault Group', 'Schneider Electric', 'Air Liquide'],
  },
  {
    id: 'bb4',
    name: 'Telco & Media Disruption',
    description: 'Telco en pleine transformation BSS/OSS. Agentforce pour moderniser le service client et les ops.',
    category: 'Telco & Media',
    quarters: ['Q4'],
    priority: 'medium',
    opportunityIds: ['o6', 'o8'],
    status: 'at_risk',
    owner: 'Pierre Medevielle',
    targetRevenue: 3050000,
    currentRevenue: 0,
    keyAccounts: ['Orange', 'Air France', 'TF1 Group'],
  },
  {
    id: 'bb5',
    name: 'Public Sector & Mobilité',
    description: 'Mobilité et services publics : SNCF, RATP. Agentforce pour moderniser l\'expérience voyageur.',
    category: 'Public Sector',
    quarters: ['Q3', 'Q4'],
    priority: 'medium',
    opportunityIds: ['o11'],
    status: 'on_track',
    owner: 'Pierre Medevielle',
    targetRevenue: 1500000,
    currentRevenue: 750000,
    keyAccounts: ['SNCF', 'RATP', 'La Poste'],
  },
]

export const fundings: Funding[] = [
  {
    id: 'f1',
    name: 'Catalyst POC Total Energies',
    type: 'Catalyst',
    amount: 150000,
    currency: 'EUR',
    status: 'approved',
    opportunityId: 'o1',
    account: 'Total Energies',
    dateSubmitted: '2026-05-01',
    dateApproved: '2026-05-20',
    owner: 'Pierre Medevielle',
    useCase: 'POC Agentforce Service - automatisation traitements incidents',
    quarter: 'Q3',
  },
  {
    id: 'f2',
    name: 'Catalyst Pilot LVMH',
    type: 'Catalyst',
    amount: 200000,
    currency: 'EUR',
    status: 'submitted',
    opportunityId: 'o2',
    account: 'LVMH',
    dateSubmitted: '2026-05-28',
    owner: 'Pierre Medevielle',
    useCase: 'Pilot Agentforce Sales - personalisation clientèle luxury',
    quarter: 'Q3',
  },
  {
    id: 'f3',
    name: 'SIP BNP Paribas Digital Transformation',
    type: 'SIP',
    amount: 500000,
    currency: 'EUR',
    status: 'approved',
    opportunityId: 'o3',
    account: 'BNP Paribas',
    dateSubmitted: '2026-04-15',
    dateApproved: '2026-05-10',
    owner: 'Pierre Medevielle',
    useCase: 'Co-innovation Agentforce Platform - use cases bancaires',
    quarter: 'Q4',
  },
  {
    id: 'f4',
    name: 'Catalyst Orange Telco Pilot',
    type: 'Catalyst',
    amount: 175000,
    currency: 'EUR',
    status: 'draft',
    opportunityId: 'o8',
    account: 'Orange',
    owner: 'Pierre Medevielle',
    useCase: 'Pilot Agentforce Service - centre d\'appels 1er niveau',
    quarter: 'Q4',
  },
  {
    id: 'f5',
    name: 'SIP Société Générale FS Innovation',
    type: 'SIP',
    amount: 400000,
    currency: 'EUR',
    status: 'approved',
    opportunityId: 'o4',
    account: 'Société Générale',
    dateSubmitted: '2026-03-20',
    dateApproved: '2026-04-25',
    owner: 'Pierre Medevielle',
    useCase: 'Co-développement Agentforce for Financial Services',
    quarter: 'Q3',
  },
  {
    id: 'f6',
    name: 'Catalyst AXA Insurance POC',
    type: 'Catalyst',
    amount: 125000,
    currency: 'EUR',
    status: 'submitted',
    opportunityId: 'o9',
    account: 'AXA',
    dateSubmitted: '2026-06-01',
    owner: 'Pierre Medevielle',
    useCase: 'POC Agentforce Claims - automatisation traitement sinistres',
    quarter: 'Q3',
  },
  {
    id: 'f7',
    name: 'SIP Capgemini GSI Partnership',
    type: 'SIP',
    amount: 600000,
    currency: 'EUR',
    status: 'draft',
    opportunityId: 'o12',
    account: 'Capgemini',
    owner: 'Pierre Medevielle',
    useCase: 'Programme partenaire GSI Agentforce - enablement + incentives',
    quarter: 'Q4',
  },
  {
    id: 'f8',
    name: 'Catalyst Renault MFG POC',
    type: 'Catalyst',
    amount: 150000,
    currency: 'EUR',
    status: 'submitted',
    opportunityId: 'o7',
    account: 'Renault Group',
    dateSubmitted: '2026-06-02',
    owner: 'Pierre Medevielle',
    useCase: 'POC Agentforce Manufacturing - maintenance prédictive + field service',
    quarter: 'Q4',
  },
]

export function getTotalPipeline(opps: Opportunity[]): number {
  return opps.filter(o => o.stage !== '8 - Closed Lost').reduce((sum, o) => sum + o.amount, 0)
}

export function getWeightedPipeline(opps: Opportunity[]): number {
  return opps.filter(o => o.stage !== '8 - Closed Lost').reduce((sum, o) => sum + o.amount * (o.probability ?? 0) / 100, 0)
}

export function getQ3Pipeline(opps: Opportunity[]): number {
  return opps.filter(o => o.quarter === 'Q3' && o.stage !== '7 - Closed Won' && o.stage !== '8 - Closed Lost').reduce((sum, o) => sum + o.amount, 0)
}

export function formatAmount(n: number): string {
  if (n >= 1000000) return `${(n / 1000000).toFixed(1)}M€`
  if (n >= 1000) return `${(n / 1000).toFixed(0)}K€`
  return `${n}€`
}
